Redirect all errors to stderr

diff --git a/email b/email
--- a/email
+++ b/email
@@ -69,7 +69,7 @@ if [ -n "$QUEUE" ]; then
 fi
 
 if [ -z "$FROM" ]; then
-    echo "ERROR:FROM is not defined"
+    echo "ERROR:FROM is not defined" 1>&2
     exit 1
 fi
 
@@ -161,7 +161,7 @@ if [ $# -eq 6 ]; then
     MAILFILE=$6
 else
     MAILFILE=$(mktemp </dev/null /tmp/fax.XXXXXX) ||
-        (echo "ERROR:Failed to create temporary file"; exit 1)
+        (echo "ERROR:Failed to create temporary file" 1>&2; exit 1)
     cat >$MAILFILE
 fi
 
